# Generated by Django 6.0.3 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_size_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteMaintenanceSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_key", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("whole_site_maintenance", models.BooleanField(default=False)),
                ("products_maintenance", models.BooleanField(default=False)),
                ("sign_maintenance", models.BooleanField(default=False)),
                ("checkout_maintenance", models.BooleanField(default=False)),
                (
                    "maintenance_message",
                    models.CharField(
                        blank=True,
                        default="We are doing scheduled maintenance. Please try again shortly.",
                        max_length=255,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Maintenance Settings",
                "verbose_name_plural": "Site Maintenance Settings",
                "db_table": "site_maintenance_settings",
            },
        ),
    ]
