# Generated by Django 6.0.4 on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_sitemaintenancesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160)),
                ("subtitle", models.CharField(blank=True, default="", max_length=255)),
                ("eyebrow", models.CharField(blank=True, default="", max_length=80)),
                ("cta_label", models.CharField(blank=True, default="", max_length=50)),
                ("cta_url", models.CharField(blank=True, default="", max_length=300)),
                ("image_url", models.URLField(blank=True, default="", max_length=1000)),
                ("image_file", models.ImageField(blank=True, null=True, upload_to="hero_slides/")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hero_slides",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
