# Generated by Django 6.0.4 on 2026-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_coupon_code_order_discount_amount_coupon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnrequest",
            name="resolution",
            field=models.CharField(
                choices=[("refund", "Refund"), ("return", "Return")],
                default="refund",
                max_length=10,
            ),
        ),
    ]
