# Generated by Django 6.0.4 on 2026-06-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_returnrequest_resolution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnrequest",
            name="refund_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Refunded", "Refunded"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="returnrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Requested", "Requested"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Resolved", "Resolved"),
                ],
                default="Requested",
                max_length=20,
            ),
        ),
    ]
